### ISSUE TITLE
jsx not supported (Unexpected token "<")

### ISSUE THREAD

**Issue by MareoRaft** [zxol/react-component-publish#1]
When I run `npm run build`, I get the error:

    ERROR in ./srctest/app.js 7:4
    Module parse failed: Unexpected token (7:4)
    You may need an appropriate loader to handle this file type.
    | const ParentWrapper = () => {
    |   return (
    >     <div
    |       style={{
    |         display: 'flex',
     @ multi (webpack)-dev-server/client?http://localhost:9000 ./srctest/app.js main[1]

This problem may not be specific to your setup in particular.  I've been trying to publish my own React component and keep running into this error.  It's as-if .babelrc is being ignored or similar.  Your help is greatly appreciated.

**Comment by zxol** [comment]
Did you mean `npm run dev`?

what's the output for `npm run build`? Same issue?

**Comment by zxol** [comment]
If you do a temporary rename/delete of `.babelrc` do you get the same error?

**Comment by MareoRaft** [comment]
Both `npm run dev` and `npm run build` give the same error.

I am get the same error regardless of the presence of babelrc.  I also tried putting the babel config directly in my package.json (which is alternative way to specify your babel config), and get the same error.

Rewriting the jsx in pure JavaScript gets me passed the error and builds successfully.  But this solution is not good enough, because the component I wish to ultimately publish will use a bunch of other babel features.  For example, we use arrow functions within classes (e.g. `render = () => {`) which I have confirmed causes another error.  So it seems to be some sort of babel issue...

**Comment by MareoRaft** [comment]
Found a lot of info [here](https://github.com/babel/babel-loader/issues/552).  Unfortunately, none of these things has worked for me yet.

**Comment by zxol** [comment]
I'm unable to reproduce the error on my devices.  My best guess would be some kind of environment specific bug in babel loader. I've updated the dependencies for this package to their latest versions.

**Comment by MareoRaft** [comment]
Ah, yeah.  Thanks anyway.
